name: Add Label

on:
  issues:
    types: closed
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Fetch Last Comment
        id: last_comment
        run: |
          issue_number=${{ github.event.issue.number }}
          comments_url="https://api.github.com/repos/Automattic/wp-calypso-test-results/issues/${issue_number}/comments"
          last_comment=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $comments_url | jq -r '.[-1].body')
          echo "::set-output name=last_comment::$last_comment"

      - name: Set Last Comment as Environment Variable
        id: set_last_comment
        run: |
          last_comment="${{ steps.last_comment.outputs.last_comment }}"
          echo "LAST_COMMENT=$last_comment" >> $GITHUB_ENV

      - name: Check Last Comment with Regex
        id: regex_match
        run: |
          last_comment="${{ steps.last_comment.outputs.last_comment }}"
          if [[ "$last_comment" =~ ([S|s]tale)+.*([C|c]losed)+ ]]; then
            echo "::set-output name=regex_matched::true"
          else
            echo "::set-output name=regex_matched::false"
          fi

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.regex_match == 'true'
        with:
          labels: wontfix
