name: Add Label

on:
  issues:
    types: [closed]
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
          
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(env.last_comment, '([S|s]tale)+.*([C|c]losed)+') }}
        env:
          last_comment: ${{ "${{ github.event.issue.body }}" | tail -n 1 }}
        with:
          labels: wontfix
