name: Add Label

on:
  issues:
    types: closed
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get comments
        uses: octokit/request-action@v2.x
        id: get_comments
        with:
          route: GET /repos/Automattic/wp-calypso-test-results/issues/${{ github.event.issue.number }}/comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get last comment
        run: |
          echo ${{ steps.get_comments.outputs.data }} | jq -r '.[].body' | while IFS= read -r comment; do
            echo "Comment: $comment"
            # You can perform further processing on each comment here
          done
          
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(env.LAST_COMMENT, '([S|s]tale)+.*([C|c]losed)+') }}
        with:
          labels: wontfix
