name: Add Label

on:
  issues:
    types: closed
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get all comments for an issue
        uses: octokit/request-action@v2.x
        id: get_all_comments
        with:
          route: GET /repos/${{github.repository}}/issues/${{ github.event.issue.number }}/comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract last comment
        id: extract_last_comment
        run: |
          last_comment=$( echo '${{ steps.get_comments.outputs.data }}' | jq -r '.[-1].body' )
          echo "::set-output name=last_comment::$last_comment"

      - name: Add [Closed] Stale label
        id: add_closed_stale_label
        uses: actions-ecosystem/action-add-labels@v1
        if: contains( env.LAST_COMMENT, 'Since this issue has been inactive for quite some time, KitKat has made the decision to close it.' )
        with:
          labels: wontfix
