name: Add Label

on:
  issues:
    types: [opened, closed]
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.comment.body, '([S|s]tale)+.*([C|c]losed)+') }}
        with:
          labels: wontfix
