name: Add Label

on:
  issues:
    types: closed
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get comments
        uses: octokit/request-action@v2.x
        id: get_comments
        with:
          route: GET /repos/Automattic/wp-calypso-test-results/issues/${{ github.event.issue.number }}/comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Last Comment
        id: last_comment
        run: |
          last_comment=$( echo '${{ steps.get_comments.outputs.data }}' | jq -r '.[-1].body' )
          echo "::set-output name=last_comment::$last_comment"

      - name: Set Last Comment as Environment Variable
        id: set_last_comment
        run: |
          last_comment="${{ steps.last_comment.outputs.last_comment }}"
          echo "LAST_COMMENT=$last_comment" >> $GITHUB_ENV

      - name: Add [Closed] Stale label
        uses: actions-ecosystem/action-add-labels@v1
        if: contains( env.LAST_COMMENT, 'Since this issue has been inactive for quite some time, KitKat has made the decision to close it.' )
        with:
          labels: wontfix
