name: Add Label

on:
  issues:
    types: [closed]
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get Last Comment
        id: last_comment
        run: |
          last_comment=$(echo "${{ github.event.issue.body }}" | tail -n 1)
          echo "::set-output name=last_comment::$last_comment"
          
      # - name: add label
      #   uses: actions-ecosystem/action-add-labels@v1
      #   if: ${{ contains(env.last_comment, '([S|s]tale)+.*([C|c]losed)+') }}
      #   with:
      #     labels: wontfix
