name: Add Label

on:
  issues:
    types: closed
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Fetch Last Comment
        id: last_comment
        run: |
          issue_number=${{ github.event.issue.number }}
          comments_url="https://api.github.com/repos/Automattic/wp-calypso-test-results/issues/${issue_number}/comments"
          last_comment=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $comments_url | jq -r '.[-1].body')
          echo "::set-output name=last_comment::$last_comment"

      - name: Set Last Comment as Environment Variable
        id: set_last_comment
        run: |
          last_comment="${{ steps.last_comment.outputs.last_comment }}"
          echo "LAST_COMMENT=$last_comment" >> $GITHUB_ENV

      - name: Add [Closed] Stale label
        uses: actions-ecosystem/action-add-labels@v1
        if: contains( env.LAST_COMMENT, 'Since this issue has been inactive for quite some time, KitKat has made the decision to close it.' )
        with:
          labels: wontfix
