name: Add Label

on:
  issues:
    types: closed
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/Automattic/wp-calypso-results/issues/21/comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo comment: '${{ steps.get_latest_release.outputs.data }}'
          echo issue details: '${{ github.events }}'
          
      # - name: add label
      #   uses: actions-ecosystem/action-add-labels@v1
      #   if: ${{ contains(env.last_comment, '([S|s]tale)+.*([C|c]losed)+') }}
      #   with:
      #     labels: wontfix
