# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Generate updated Allure report

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["trunk"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions: write-all

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
env:
  REPORT_PATH: ${{ github.workspace }}/docs/report
  
jobs:
  publish_pr_test_reports:
    name: Publish Pre-Release Allure reports
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Install allure-commandline package
        run: npm install -g allure-commandline
      
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: repo
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
          
      - name: Locate newest Allure results
        working-directory: repo/data
        run: |
          LATEST_RESULT=$(ls -f  | cut -d_ -f3 | sort -n | tail -1)
          echo "LATEST_ALLURE_RESULT=$LATEST_RESULT" >> $GITHUB_ENV
      - name: Generate report with history
        working-directory: repo
        env:
          ALLURE_RESULTS_DATA_BASE_PATH: ${{github.workspace}}/data
        run: |
          echo "latest allure result dir" ${{env.LATEST_ALLURE_RESULT}}
          
          echo "history dir in latest allure results dir" $ALLURE_RESULTS_DATA_BASE_PATH/$LATEST_ALLURE_RESULT/history
          mkdir -p $ALLURE_RESULTS_DATA_BASE_PATH/$LATEST_ALLURE_RESULT/history
          ls -la $ALLURE_RESULTS_DATA_BASE_PATH/$LATEST_ALLURE_RESULT/
          
          echo "current report history path" $REPORT_PATH/history/*
          echo "workspace"
          ls -la ${{github.workspace}}
          echo "workspace docs"
          ls -la ${{github.workspace}}/docs
          echo "workspace docs report "
          ls -la ${{github.workspace}}/docs/report
          
          cp -R $REPORT_PATH/history/ $ALLURE_RESULTS_DATA_BASE_PATH/$LATEST_ALLURE_RESULT/history
          allure generate --clean $ALLURE_RESULTS_DATA_BASE_PATH/$LATEST_ALLURE_RESULT --output $OUTPUT_PATH
      - name: Push changes to branch
        env:
          GITHUB_USER: ${{ secrets.REPORTS_USER }}
          GITHUB_EMAIL: ${{ secrets.REPORTS_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
          BOT_COMMIT_MESSAGE: "regenerated report using data from ${{github.event_name}}"
        run: |
          git config user.name ${{env.GITHUB_USER}}
          git config user.email ${{env.GITHUB_EMAIL}}
          git add docs/report
          git commit -m "GitHub Actions: ${{env.BOT_COMMIT_MESSAGE}}"
