# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Generate updated Allure report

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["trunk"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      newest_allure_results:
        required: true
  repository_dispatch:
    types:
      - webhook

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
env:
  REPORT_PATH: ${{ github.workspace }}/docs/report
  LATEST_RESULT: ${{github.event.inputs.newest_allure_results}}
  
jobs:
  generate_allure_report:
    name: Generate Pre-Release Allure reports
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Download report from S3
        env:
          SOURCE: ${{ secrets.AWS_S3_BUCKET_BASE_URL }}/
          DESTINATION: ${{ github.workspace }}
        run: | 
          aws s3 cp $SOURCE $DESTINATION
          ls -la $DESTINATION
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the generated report
          path: ${{env.REPORT_PATH}}
          
#       - name: Locate newest Allure results
#         working-directory: data/
#         run: |
#           echo "LATEST_ALLURE_RESULT=$(ls -F | cut -d_ -f3 | sort -n | tail -1)" >> $GITHUB_ENV
          
#       - name: Generate report with history
#         working-directory: scripts/
#         env:
#           ALLURE_RESULTS_DATA_BASE_PATH: ${{github.workspace}}/data
#         run: bash regenerate-report.sh
          
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v1
#         with:
#           # Upload the generated report
#           path: ${{env.REPORT_PATH}}

#       - name: Push changes to trunk
#         uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
#         env:
#           BOT_COMMIT_MESSAGE: "regenerated report using data from run ${{env.LATEST_ALLURE_RESULT}}"
#         with:
#           add: 'docs/report'
#           push: true
#           message: ${{env.BOT_COMMIT_MESSAGE}}'

  publish:
    name: Publish
    needs: generate_allure_report
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
            
